### ISSUE TITLE
Check:imports command wrong reports

### ISSUE THREAD

**Issue by alikhosravidev** [imanghafoori1/php_token_analyzer#16]
PHP: v8.1
Laravel: v9
microscope: v1.0.318
Os: Pop Os

Autoload psr4:
![image](https://github.com/imanghafoori1/laravel-microscope/assets/49164621/4740ca38-ac50-4730-a38e-60b40e91ddb9)

Wrong reports:
![image](https://github.com/imanghafoori1/laravel-microscope/assets/49164621/68024775-e1f5-4b1f-a7c5-843b43714b29)

Reported message:
1 Extra Import:
   Illuminate\Contracts\Support\Arrayable
at app/Core/Notification/Http/Resources/API/V1/NotificationUserResource.php:7

![image](https://github.com/imanghafoori1/laravel-microscope/assets/49164621/1b6bd90f-f4a7-4157-9ac4-3c80bedbfcb2)

Reported message:
1 Extra Import:
   App\Core\User\Entities\User
at app/Core/BI/View/Widgets/UserInsight.php:7

![image](https://github.com/imanghafoori1/laravel-microscope/assets/49164621/ac3985e8-3a3c-44f0-a92b-27843813f8ff)

Reported message:
1 Unused & wrong import:
   use EnumHasPersianListTrait;
at app/Modules/LMS/Product/Enums/ProductAgeRange.php:9

**Comment by alikhosravidev** [comment]
However, I was able to solve question mark problem in the following way

![image](https://github.com/imanghafoori1/php_token_analyzer/assets/49164621/19e78ff7-8dac-4bc7-8d4f-c26734605b1b)

Of course, provided that the question mark is at the beginning of the sentence 

Like this:
`/** @var ?User $user */`

Did you find this helpful?

**Comment by imanghafoori1** [comment]
Could you please create an issue for each problem?

**Comment by alikhosravidev** [comment]
Ok, sure
