### ISSUE TITLE
Check:imports command wrong reports for return types

### ISSUE THREAD

**Issue by alikhosravidev** [imanghafoori1/php_token_analyzer#17]
PHP: v8.1
Laravel: v9
microscope: v1.0.318
Os: Pop Os

Autoload psr4:
`"autoload": {
        "files": [
            "app/helpers.php"
        ],
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },`

![image](https://github.com/imanghafoori1/php_token_analyzer/assets/49164621/ee6c5db0-769f-4347-acb0-7a873f34de79)

Reported message:
1 Extra Import:
Illuminate\Contracts\Support\Arrayable
at app/Core/Notification/Http/Resources/API/V1/NotificationUserResource.php:7

**Comment by imanghafoori1** [comment]
please paste the whole php file content here since reproducing the issue is hard.

**Comment by alikhosravidev** [comment]
`<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    public function index(): array|\JsonSerializable|Arrayable
    {
        return [];
    }
}
`

I solved this problem here:
https://github.com/imanghafoori1/php_token_analyzer/pull/15
